Repository flintlib/flint, pull requests merged in 2023-10, with the labels that each got.

#1428 Added *_push_term_*_ffmpz functions to mpoly types
  doc/source/fmpq_mpoly.rst
  doc/source/fmpz_mod_mpoly.rst
  doc/source/fmpz_mpoly.rst
  doc/source/fq_nmod_mpoly.rst
  doc/source/nmod_mpoly.rst
  src/fmpq_mpoly.h
  src/fmpq_mpoly/push_term_fmpq_fmpz.c
  src/fmpq_mpoly/test/t-push_term_fmpq_fmpz.c
  src/fmpz_mod_mpoly.h
  src/fmpz_mod_mpoly/push_term_fmpz_fmpz.c
  src/fmpz_mod_mpoly/test/t-push_term_fmpz_fmpz.c
  src/fmpz_mpoly.h
  src/fmpz_mpoly/push_term_fmpz_fmpz.c
  src/fmpz_mpoly/test/t-push_term_fmpz_fmpz.c
  src/fq_nmod_mpoly.h
  src/fq_nmod_mpoly/push_term_fq_nmod_fmpz.c
  src/fq_nmod_mpoly/test/t-push_term_fq_nmod_fmpz.c
  src/nmod_mpoly.h
  src/nmod_mpoly/push_term_ui_fmpz.c
  src/nmod_mpoly/test/t-push_term_ui_fmpz.c
Labels: new feature, needs review

#1437 adding missing single headers
  Makefile.in
Labels: 3.0, needs review, build system

#1446 Fix bootstrap.sh for autotools 2.69
  bootstrap.sh
Labels: needs review

#1452 Limit concurrency of CI jobs
  .github/workflows/CI.yml
Labels: workshop 2023

#1454 fix some small typos
  doc/source/acb_poly.rst
  doc/source/arb_poly.rst
  doc/source/fexpr.rst
  doc/source/gr_mat.rst
  src/bool_mat/all_pairs_longest_walk.c
  src/fft_small.h
Labels: needs review

#1453 Remove fq_zech_vec from HEADER_DIRS in Makefile.in
  Makefile.in
Labels: workshop 2023

#1442 Commenting out unused function `pairs_insert_unique is unused`
  src/fmpz_mpoly/buchberger_naive.c
Labels: workshop 2023

#1440 variable 'status' set but not used
  src/gr/ca.c
Labels: workshop 2023

#1463 Deinline `flint_mpn_get_d`
  src/fmpz/get_d.c
  src/fmpz/get_d_2exp.c
  src/gmpcompat.h
  src/mpn_extras.h
  src/mpn_extras/get_d.c
Labels: workshop 2023

#1466 fmpz_poly_factor_squarefree: handle the zero polynomial
  src/fmpz_poly_factor/factor_squarefree.c
  src/fmpz_poly_factor/test/t-factor_squarefree.c
Labels: workshop 2023, bug

#1467 Fix a few more memory leaks, round 2
  src/fmpz_mod_poly/test/t-sub_series.c
  src/fmpz_poly/test/t-eulerian_polynomial.c
  src/fmpz_poly_factor/test/t-zassenhaus_subset.c
  src/nf_elem/test/t-mul_div_fmpq.c
  src/qfb/exponent_grh.c
  src/qfb/test/t-exponent.c
  src/qfb/test/t-exponent_element.c
  src/qfb/test/t-exponent_grh.c
  src/qfb/test/t-nucomp.c
  src/qfb/test/t-nudupl.c
  src/qfb/test/t-prime_form.c
  src/qfb/test/t-reduced_forms.c
Labels: workshop 2023, bug

#1468 CI: limit which branches run CI tests
  .github/workflows/CI.yml
Labels: CI, workshop 2023

#1451 update cross-platform-action to improve reliability?
  .github/workflows/CI.yml
Labels: workshop 2023

#1473 CI Cygwin GCC: reduce multiplier from 1 to 0.5
  .github/workflows/CI.yml
Labels: CI, workshop 2023

#1438 Fix `configure' helpstring for older version of bash
  configure.ac
Labels: workshop 2023, needs review

#1462 Also regenerate doc when workflow is modified
  .github/workflows/docs.yml
Labels: workshop 2023, needs review

#1469 using FLINT_UNUSED instead of __attribute__((unused))
  examples/functions_benchmark.c
Labels: workshop 2023

#1483 README.md: Add some badges
  README.md
Labels: workshop 2023

#1464 Remove dum dummy-functions
  Makefile.in
  src/fmpz_lll/babai.c
  src/fmpz_lll/d_lll.c
  src/fmpz_lll/mpf2_lll.c
Labels: workshop 2023

#1443 fabs to FLINT_ABS
  src/flint.h
  src/fmpz_mod_vec/set_fmpz_vec.c
Labels: workshop 2023

#1475 pthread -> thread_pool in Arb
  doc/source/flint.rst
  src/acb_dft/rad2_threaded.c
  src/acb_dirichlet/platt_multieval_threaded.c
  src/acb_mat/mul_threaded.c
  src/acb_poly/powsum_series_naive_threaded.c
  src/arb_mat/mul_threaded.c
  src/thread_support.h
  src/thread_support/thread_support.c
Labels: workshop 2023, bug

#1493 adding function for testing if nmod_poly is monic
  src/nmod_poly.h
Labels: good first issue, needs review

#1497 Doc nmod poly is stuff
  doc/source/nmod_poly.rst
Labels: workshop 2023, documentation, needs review

#1494 Support zero(), one(), set_ui() etc. for fixed-length generic vector space elements
  src/gr/vector.c
  src/python/flint_ctypes.py
Labels: workshop 2023, bug

#1498 Basic printing functions for nmod_vec
  doc/source/nmod_mat.rst
  doc/source/nmod_vec.rst
  src/nmod_vec.h
  src/nmod_vec/io.c
Labels: workshop 2023, needs review

#1417 No standard configure constants in public headers
  .gitignore
  Makefile.in
  configure.ac
  src/flint-config.h.in
  src/flint.h
Labels: workshop 2023, needs review, build system

#1489 header-only ntl interface
  Makefile.in
  configure.ac
  src/NTL-interface.h
  src/interfaces/NTL-interface.cpp
  src/interfaces/doc/interfaces.txt
  src/interfaces/test/t-NTL-interface.cpp
Labels: workshop 2023

#1496 Add new function `arb_minmax`
  doc/source/arb.rst
  src/arb.h
  src/arb/max.c
  src/arb/min.c
  src/arb/minmax.c
  src/arb/test/t-max.c
  src/arb/test/t-min.c
  src/arb/test/t-minmax.c
Labels: workshop 2023, new feature

#1506 fix detection of ldconfig
  configure.ac
Labels: workshop 2023

#1525 _acb_poly_zeta_em_sum: Remove unused term variable
  src/acb_poly/zeta_em_sum.c
Labels: workshop 2023

#1449 Enhance 'make dist', add GitHub release workflow
  .github/workflows/release.yml
  .gitignore
  CMakeLists.txt
  Makefile.in
  VERSION
  bootstrap.sh
  configure.ac
  dev/make_dist.sh
  doc/source/conf.py
  src/flint.h.in
Labels: workshop 2023, build system

#1524 Helper functions from j-kieffer/acb_theta
  doc/source/acb.rst
  doc/source/acb_mat.rst
  doc/source/arb.rst
  doc/source/arb_mat.rst
  doc/source/fmpz_mat.rst
  src/acb.h
  src/acb/io.c
  src/acb/sqrts.c
  src/acb/test/t-sqrts.c
  src/acb/test/t-urandom.c
  src/acb/test/t-vec_set_real_imag.c
  src/acb/urandom.c
  src/acb_dirichlet/test/t-platt_multieval.c
  src/acb_dirichlet/test/t-platt_multieval_threaded.c
  src/acb_mat.h
  src/acb_mat/get_imag.c
  src/acb_mat/get_real.c
  src/acb_mat/onei.c
  src/acb_mat/set_real_imag.c
  src/acb_mat/test/t-set_real_imag.c
  src/acb_mat/test/t-vector_mul.c
  src/acb_mat/vector_mul.c
  src/arb.h
  src/arb/io.c
  src/arb/randtest.c
  src/arb_mat.h
  src/arb_mat/bilinear_form.c
  src/arb_mat/randtest_cho.c
  src/arb_mat/randtest_spd.c
  src/arb_mat/spd_get_fmpz_mat.c
  src/arb_mat/spd_is_lll_reduced.c
  src/arb_mat/spd_lll_reduce.c
  src/arb_mat/test/t-bilinear_form.c
  src/arb_mat/test/t-spd_get_fmpz_mat.c
  src/arb_mat/test/t-spd_lll_reduce.c
  src/arb_mat/test/t-vector_mul.c
  src/arb_mat/vector_mul.c
  src/fmpz_mat.h
  src/fmpz_mat/is_spd.c
  src/fmpz_mat/test/t-is_spd.c
Labels: workshop 2023

#1555 Fix bug in nmod poly mat window init
  src/nmod_poly_mat/window_init.c
Labels: bug, needs review
